pipeline {
    agent any

    tools {
        maven 'Default Maven'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Gopireddymadhava/jenkins_sonarqube_project.git'
            }
        }

        stage('Build and SonarQube Analysis') {
            steps {
                dir('poppy') {
                    sh 'chmod +x mvnw'
                    withSonarQubeEnv('Sonar-Server') {
                        sh './mvnw clean verify sonar:sonar -Dsonar.projectKey=Onix-Website-Scan'
                    }
                }
            }
        }
    }
}
