pipeline {
    agent any

    tools {
        maven 'Default Maven'
    }

    environment {
        REMOTE_HOST = '3.95.67.56'
        REMOTE_USER = 'ec2-user'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Gopireddymadhava/jenkins_sonarqube_project.git'
            }
        }

        stage('Build and SonarQube Analysis') {
            steps {
                dir('poppy') {
                    sh 'chmod +x mvnw'
                    withSonarQubeEnv('Sonar-Server') {
                        sh './mvnw clean verify sonar:sonar -Dsonar.projectKey=Onix-Website-Scan'
                    }
                }
            }
        }

        stage('Test SSH to Docker EC2') {
            steps {
                sshagent(['docker-ec2-ssh']) {
                    sh '''
                        ssh -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOST} '
                            echo "Connected successfully"
                            hostname
                            whoami
                            docker ps
                        '
                    '''
                }
            }
        }
    }
}
